name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: List all files
      run: |
        ls -a
    
    - name: Install dependencies
      run: |
        ls
        pip install -r requirements.txt
